docker_image: &docker_image
  docker:
    - image: docker:19.03.6

slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.4.0

work_directory: &work_directory
  working_directory: ~/drone-yaml-validator

resource_class: &resource_class
  resource_class: small

version: 2.1
jobs:
  groovy_script_to_jar:
    docker:
      - image: devatherock/vela-groovy-script-to-jar:0.6.0
    <<: *resource_class
    <<: *work_directory
    environment:
      PARAMETER_SCRIPT_PATH: YamlValidator.groovy
      PARAMETER_STATIC_COMPILE: true
      VELA: true
      PARAMETER_OUTPUT_FILE: build/native/libs/YamlValidator.jar
    steps:
      - checkout
      - run: sh /scripts/entry-point.sh
      - persist_to_workspace:
          root: ~/drone-yaml-validator
          paths:
            - build
  java_to_native:
    docker:
      - image: devatherock/java-to-native:0.1.0
    <<: *resource_class
    <<: *work_directory
    environment:
      PLUGIN_JAR_NAME: YamlValidator.jar
      PLUGIN_CONFIG_FILE: config/graal.yml
    steps:
      - checkout
      - attach_workspace:
          at: ~/drone-yaml-validator
      - run: sh /scripts/entry-point.sh
      - persist_to_workspace:
          root: ~/drone-yaml-validator
          paths:
            - YamlValidator
  publish:
    <<: *docker_image
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/drone-yaml-validator
      - run: |
          TAG=1.1.0
          docker build -t devatherock/drone-yaml-validator:$TAG .
          docker tag devatherock/drone-yaml-validator:$TAG devatherock/drone-yaml-validator:latest
          docker tag devatherock/drone-yaml-validator:$TAG devatherock/vela-yaml-validator:$TAG
          docker tag devatherock/drone-yaml-validator:$TAG devatherock/vela-yaml-validator:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/drone-yaml-validator:$TAG
          docker push devatherock/drone-yaml-validator:latest
          docker push devatherock/vela-yaml-validator:$TAG
          docker push devatherock/vela-yaml-validator:latest
          
  test:
    docker:
      - image: devatherock/java-with-docker:adoptopenjdk-11
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - restore_cache:
          keys:   
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: |
          ./gradlew build --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}            

  notify_success:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#33ad7f"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack
  notify_failure:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Failure: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#a1040c"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run:
          name: Failure notification
          command: /bin/simpleslack
          when: on_fail

workflows:
  version: 2.1
  build_publish:
    jobs:
      - groovy_script_to_jar:
          filters:
            branches:
              only: master
      - java_to_native:
          requires:
            - groovy_script_to_jar
      - publish:
          requires:
            - java_to_native
      - test:
          requires:
            - publish
      - notify_success:
          requires:
            - test
      - notify_failure:
          requires:
            - test
  pr_check:
    jobs:
      - groovy_script_to_jar:
          filters:
            branches:
              ignore: master