docker_image: &docker_image
  docker:
    - image: docker:19.03.6
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD

slack_image: &slack_image
  docker:
    - image: devatherock/simple-slack:0.4.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    
yaml_validator_image: &yaml_validator_image
  docker:
    - image: devatherock/vela-yaml-validator:1.2.0
      auth:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
        
orbs:
  gradle: circleci/gradle@2.2.0

work_directory: &work_directory
  working_directory: ~/drone-yaml-validator

resource_class: &resource_class
  resource_class: small

executors:
  jdk-executor:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory

version: 2.1
jobs:
  groovy_script_to_jar:
    docker:
      - image: devatherock/vela-groovy-script-to-jar:0.6.2
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory
    environment:
      PARAMETER_SCRIPT_PATH: src/main/groovy/io/github/devatherock/yamlvalidator/YamlValidator.groovy
      PARAMETER_STATIC_COMPILE: true
      PARAMETER_OUTPUT_FILE: build/native/libs/YamlValidator.jar
    steps:
      - checkout
      - run: sh /scripts/entry-point.sh
      - persist_to_workspace:
          root: ~/drone-yaml-validator
          paths:
            - build
  java_to_native:
    docker:
      - image: devatherock/java-to-native:0.1.2
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    resource_class: medium
    <<: *work_directory
    environment:
      PLUGIN_JAR_NAME: build/native/libs/YamlValidator.jar
      PLUGIN_CONFIG_FILE: config/graal.yml
    steps:
      - checkout
      - attach_workspace:
          at: ~/drone-yaml-validator
      - run: sh /scripts/entry-point.sh
      - persist_to_workspace:
          root: ~/drone-yaml-validator
          paths:
            - YamlValidator

  test_binary:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - attach_workspace:
          at: ~/drone-yaml-validator
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: |
          ./gradlew test --tests '*YamlValidatorBinarySpec*' --no-daemon
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  publish:
    <<: *docker_image
    <<: *resource_class
    <<: *work_directory
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/drone-yaml-validator
      - run: |
          TAG=1.2.0
          docker build -t devatherock/drone-yaml-validator:$TAG .
          docker tag devatherock/drone-yaml-validator:$TAG devatherock/drone-yaml-validator:latest
          docker tag devatherock/drone-yaml-validator:$TAG devatherock/vela-yaml-validator:$TAG
          docker tag devatherock/drone-yaml-validator:$TAG devatherock/vela-yaml-validator:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/drone-yaml-validator:$TAG
          docker push devatherock/drone-yaml-validator:latest
          docker push devatherock/vela-yaml-validator:$TAG
          docker push devatherock/vela-yaml-validator:latest

  test_docker:
    <<: *yaml_validator_image
    <<: *resource_class
    <<: *work_directory
    environment:
      PARAMETER_SEARCH_PATH: "src/test/resources/data/valid"
    steps:
      - checkout
      - attach_workspace:
          at: ~/drone-yaml-validator
      - run: sh /scripts/entry-point.sh

  test_docker_debug:
    <<: *yaml_validator_image
    <<: *resource_class
    <<: *work_directory
    environment:
      PARAMETER_DEBUG: true
      PARAMETER_SEARCH_PATH: "src/test/resources/data/valid"
    steps:
      - checkout
      - attach_workspace:
          at: ~/drone-yaml-validator
      - run: sh /scripts/entry-point.sh

  notify_success:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Success: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#33ad7f"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run: /bin/simpleslack
  notify_failure:
    <<: *slack_image
    <<: *resource_class
    environment:
      TEXT: "Failure: {{.CircleBuildUrl}} by {{.CircleUsername}}"
      COLOR: "#a1040c"
      CHANNEL: general
      TITLE: "Build completed"
    steps:
      - run:
          name: Failure notification
          command: /bin/simpleslack
          when: on_fail

workflows:
  version: 2.1
  build_publish:
    jobs:
      - gradle/run:
          executor: jdk-executor
          context:
            - docker-credentials
          filters:
            branches:
              only: master
          command: test --tests '*YamlValidatorSpec*' coveralls
      - groovy_script_to_jar:
          context:
            - docker-credentials
          filters:
            branches:
              only: master
          requires:
            - gradle/run
      - java_to_native:
          context:
            - docker-credentials
          requires:
            - groovy_script_to_jar
      - test_binary:
          context:
            - docker-credentials
          requires:
            - java_to_native
      - publish:
          context:
            - docker-credentials
          requires:
            - test_binary
      - test_docker:
          context:
            - docker-credentials
          requires:
            - publish
      - test_docker_debug:
          context:
            - docker-credentials
          requires:
            - publish
      - notify_success:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - test_docker_debug
            - test_docker
      - notify_failure:
          context:
            - docker-credentials
            - slack-webhook
          requires:
            - test_docker_debug
            - test_docker
  pr_check:
    jobs:
      - gradle/run:
          executor: jdk-executor
          context:
            - docker-credentials
          filters:
            branches:
              ignore:
                - master
          command: test --tests '*YamlValidatorSpec*'
      - groovy_script_to_jar:
          filters:
            branches:
              ignore: master
          requires:
            - gradle/run