docker_image: &docker_image
  docker:
    - image: docker:19.03.6
    
resource_class: &resource_class    
  resource_class: small    

version: 2.1
jobs:
  groovy_script_to_jar:
    docker:
      - image: devatherock/vela-groovy-script-to-jar:2.5-alpine
    <<: *resource_class  
    working_directory: ~/drone-yaml-validator
    environment:
      PARAMETER_SCRIPT_PATH: YamlValidator.groovy
      PARAMETER_OUTPUT_FILE: docker/YamlValidator.jar
    steps:
      - checkout
      - run: sh /scripts/entry-point.sh
      - persist_to_workspace:
          root: ~/drone-yaml-validator
          paths:
            - docker/YamlValidator.jar
            
  docker_build_dry_run:
    <<: *docker_image
    <<: *resource_class
    working_directory: ~/drone-yaml-validator
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/drone-yaml-validator
      - run: docker build docker
      
  publish:
    <<: *docker_image
    <<: *resource_class
    working_directory: ~/drone-yaml-validator
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/drone-yaml-validator
      - run: |
          TAG=1.0.2
          docker build -t devatherock/drone-yaml-validator:$TAG docker
          docker tag devatherock/drone-yaml-validator:$TAG devatherock/drone-yaml-validator:latest
          docker tag devatherock/drone-yaml-validator:$TAG devatherock/vela-yaml-validator:$TAG
          docker tag devatherock/drone-yaml-validator:$TAG devatherock/vela-yaml-validator:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/drone-yaml-validator:$TAG
          docker push devatherock/drone-yaml-validator:latest
          docker push devatherock/vela-yaml-validator:$TAG
          docker push devatherock/vela-yaml-validator:latest
  
  notify:
    docker:
      - image: devatherock/simple-slack:0.3.0
    <<: *resource_class  
    environment:
      PARAMETER_TEXT: "{{.CircleBuildUrl}} by {{.CircleUsername}}"
    steps:
      - run:
          name: Success notification
          command: /bin/simpleslack -c "#33ad7f"
          when: on_success
      - run:
          name: Failure notification
          command: /bin/simpleslack -c "#a1040c"
          when: on_fail
          
workflows:
  version: 2.1
  build_publish:
    jobs:
      - groovy_script_to_jar:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - groovy_script_to_jar
      - notify:
          requires:
            - publish
  pr_check:
    jobs:
      - groovy_script_to_jar:
          filters:
            branches:
              ignore: master
      - docker_build_dry_run:
          requires:
            - groovy_script_to_jar
