docker_image: &docker_image
  docker:
    - image: docker:19.03.6

version: 2
jobs:
  groovy_script_to_jar:
    docker:
      - image: devatherock/vela-groovy-script-to-jar:2.5-alpine
    working_directory: ~/drone-yaml-validator
    environment:
      PARAMETER_SCRIPT_PATH: YamlValidator.groovy
      PARAMETER_OUTPUT_FILE: docker/YamlValidator.jar
    steps:
      - checkout
      - run: sh /scripts/entry-point.sh
      - persist_to_workspace:
          root: ~/drone-yaml-validator
          paths:
            - docker/YamlValidator.jar
  docker_build_dry_run:
    <<: *docker_image
    working_directory: ~/drone-yaml-validator
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/drone-yaml-validator
      - run: docker build docker
  publish:
    <<: *docker_image
    working_directory: ~/drone-yaml-validator
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/drone-yaml-validator
      - run: |
          TAG=1.0.2
          docker build -t devatherock/drone-yaml-validator:$TAG -t devatherock/vela-yaml-validator:$TAG docker
          docker build -t devatherock/drone-yaml-validator:latest -t devatherock/vela-yaml-validator:latest docker
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/drone-yaml-validator:$TAG
          docker push devatherock/drone-yaml-validator:latest
          docker push devatherock/vela-yaml-validator:$TAG
          docker push devatherock/vela-yaml-validator:latest

workflows:
  version: 2
  build_publish:
    jobs:
      - groovy_script_to_jar:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - groovy_script_to_jar
  pr_check:
    jobs:
      - groovy_script_to_jar:
          filters:
            branches:
              ignore: master
      - docker_build_dry_run:
          requires:
            - groovy_script_to_jar