native-image:
  build:
    override-args:
      - '--no-server'
      - '--report-unsupported-elements-at-runtime'
      - '--allow-incomplete-classpath'
      - "-J-Xmx3072m"
      - "-Dgroovy.grape.enable=false"
      - "-H:IncludeResourceBundles=net.sourceforge.argparse4j.internal.ArgumentParserImpl"
      - "-H:ConfigurationFileDirectories=build/native/graal-config/"
  agent:
    args:
      - ['--debug', 'false', '--path', 'src/test/resources/data/valid']
      - ['--debug', 'false', '--path', 'src/test/resources/data/invalid']
      - ['--debug', 'false', '--path', 'src/test/resources/data/invalid2']
      - ['--debug', 'true', '--path', 'src/test/resources/data/valid']
      - ['--debug', 'true', '--path', 'src/test/resources/data/invalid']
      - ['--debug', 'true', '--path', 'src/test/resources/data/invalid2']
      - []
      - ['--help']